# General Jekyll Config
highlighter: rouge
url: ""
lsi: false
disqus_shortname: httpchriswoodgithubio
include: ['digests']
exclude: [LICENSE, CNAME, README.md, .gitignore, Gemfile, Gemfile.lock]
gems: [jekyll-gist]
